<?php

namespace TricksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	 public function getComments()
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.user', 'u')
            ->addSelect('u')
            ->orderBy('c.dateCreation', 'DESC')
        ;
	    
	    return $query
	      ->getQuery()
	      ->getResult()
	    ;
            
    }
}
