<?php

namespace TricksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends EntityRepository
{
	public function getTricks()
	{
	    $query = $this->createQueryBuilder('t')
	      ->innerJoin('t.images', 'i')
	      ->addSelect('i')
	      ->orderBy('t.dateCreation', 'DESC')
	    ;
	    
	    return $query
	      ->getQuery()
	      ->getResult()
	    ;
	  }
}
