<?php

namespace TricksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends EntityRepository
{
	public function getTricks()
	{
	    $query = $this->createQueryBuilder('t')
	      ->innerJoin('t.images', 'i')
	      ->addSelect('i')
	      ->orderBy('t.dateCreation', 'DESC')
	    ;
	    
	    return $query
	      ->getQuery()
	      ->getResult()
	    ;
	}

	public function getTrickDetails($id)
	{
	    $query = $this->createQueryBuilder('t')
	      ->innerJoin('t.images', 'i')
	      ->addSelect('i')
	      ->innerJoin('t.videos', 'v')
	      ->addSelect('v')
	      ->innerJoin('t.category', 'c')
	      ->addSelect('c')
	      ->innerJoin('t.comments', 'co')
	      ->addSelect('co')
		  ->innerJoin('co.user', 'u')
	      ->addSelect('u')	      
	      ->orderBy('t.dateCreation', 'DESC')
	    ;

	    $query
	      ->where('t.id = :id')
	      ->setParameter('id', $id)
	    ;
	    
	    return $query
	      ->getQuery()
	      ->getOneOrNullResult()
	    ;
	}
}
