<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Carole Guardiola <carole.guardiola@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getTricks()
    {
        $query = $this->createQueryBuilder('t')
          ->innerJoin('t.images', 'i')
          ->addSelect('i')
          ->orderBy('t.dateCreation', 'DESC')
        ;
        
        return $query
          ->getQuery()
          ->getResult()
        ;
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getTrickDetails($id)
    {
        $query = $this->createQueryBuilder('t')
          ->innerJoin('t.images', 'i')
          ->addSelect('i')
          ->innerJoin('t.videos', 'v')
          ->addSelect('v')
          ->innerJoin('t.category', 'c')
          ->addSelect('c')
          ->orderBy('t.dateCreation', 'DESC')
        ;

        $query
          ->where('t.id = :id')
          ->setParameter('id', $id)
        ;
        
        return $query
          ->getQuery()
          ->getOneOrNullResult()
        ;
    }
}
