user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

tricks:
    resource: "@TricksBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
