tricks:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

register_confirmation:
    path: /register_confirmation/{token}
    defaults:
        _controller: AppBundle:Security:check

forgot_password:
    path: /forgot_password/reset
    defaults:
        _controller: AppBundle:Security:forgotPassword

reset_password:
    path: /reset_password/{token}
    defaults:
        _controller: AppBundle:Security:resetPassword
