<?php

namespace ST\TricksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	 public function findByTrick($trick_id)
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.user', 'u')
            ->addSelect('u')
            ->orderBy('c.dateCreation', 'DESC')
        ;

	    $query
	      ->where('c.trick = :trick')
	      ->setParameter('trick', $trick_id)
	    ;
	    
	    return $query
	      ->getQuery()
	      ->getResult()
	    ;
	       
    }
}
