tricks_home:
    path:     /
    defaults: 
      _controller: AppBundle:Trick:index

tricks_view:
    path:     /tricks/details/{id}/{page}
    defaults: 
      _controller: AppBundle:Trick:view
      page: 1
    requirements:
      id: \d+
      page: \d+

tricks_add:
    path:     /tricks/ajout
    defaults: 
      _controller: AppBundle:Trick:add

tricks_edit:
    path:     /tricks/modification/{id}
    defaults: 
      _controller: AppBundle:Trick:edit
    requirements:
      id: \d+

tricks_delete:
    path:     /tricks/suppression/{id}
    defaults: 
      _controller: AppBundle:Trick:delete
    requirements:
      id: \d+

images_delete:
    path:     /tricks/suppression images/{id}
    defaults: 
      _controller: AppBundle:Image:delete
    requirements:
      id: \d+

thumbnail_delete:
    path:     /tricks/suppression image à la une/{id}
    defaults: 
      _controller: AppBundle:Thumbnail:delete
    requirements:
      id: \d+

videos_delete:
    path:     /tricks/suppression videos/{id}
    defaults: 
      _controller: AppBundle:Video:delete
    requirements:
      id: \d+

medias_edit:
    path:     /tricks/modification médias mobile/{id}
    defaults: 
      _controller: AppBundle:Trick:editMedias
    requirements:
      id: \d+

thumb_edit:
    path:     /tricks/modification image à la une/{id}
    defaults: 
      _controller: AppBundle:Trick:editThumbbyTrick
    requirements:
      id: \d+
