tricks_home:
    path:     /
    defaults: 
      _controller: TricksBundle:Trick:index

tricks_view:
    path:     /tricks/details/{id}
    defaults: 
      _controller: TricksBundle:Trick:view
    requirements:
      id: \d+

tricks_add:
    path:     /tricks/ajout
    defaults: 
      _controller: TricksBundle:Trick:add

tricks_edit:
    path:     /tricks/modification/{id}
    defaults: 
      _controller: TricksBundle:Trick:edit
    requirements:
      id: \d+

tricks_delete:
    path:     /tricks/suppression/{id}
    defaults: 
      _controller: TricksBundle:Trick:delete
    requirements:
      id: \d+