tricks_homepage:
    path:     /
    defaults: 
      _controller: TricksBundle:Trick:index

tricks_view:
    path:     /tricks/details/{id}/{slug}
    defaults: 
      _controller: TricksBundle:Trick:view
    requirements:
      id: \d+

tricks_add:
    path:     /tricks/ajout
    defaults: 
      _controller: TricksBundle:Trick:add
    requirements:
